---
title: "Meta Analysis Algorithm Aversion"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---
```{r, preparations, include = FALSE, fig.align="center"}
## Prepare Workspace ####
# Turn Off Scientific Notations
options(scipen=999)

# # Load the Required Libraries
# install.packages("haven")
# install.packages("readxl")
# install.packages("psych")
# install.packages("irr")
# install.packages("ICC")
# install.packages("metafor")
# install.packages("effectsize")

library(dplyr)
library(tidyr)
library(haven)
library(readxl)
library(psych)
library(irr)
library(ICC)
library(metafor)
library(effectsize)
library(ggplot2)
library(ggpubr)
library(gridExtra)
library("xtable")

# Clean and Set Working Directory
rm(list=ls())
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

## Read Datafile ####
library(xlsx)
meta_data <- read.xlsx("data.xlsx", sheetIndex = 1, startRow = 4)

## Data Preparations ####
# cohens_d transformation
meta_data$cohens_d <- ifelse((meta_data$aversion==1), (meta_data$cohens_d*-1), meta_data$cohens_d)
meta_data$cohens_d <- as.numeric(meta_data$cohens_d)
meta_data$cohens_d

# n transformation
meta_data$relevant_n <- as.numeric(as.character(meta_data$relevant_n))
meta_data$n <- meta_data$relevant_n
meta_data$n

meta_data$focus_n2 <- as.numeric(as.character(meta_data$focus_n2))
meta_data$focus_n2

meta_data$focus_n1 <- as.numeric(as.character(meta_data$focus_n1))
meta_data$focus_n1

# study_no transformation
meta_data$study_no <- as.character(meta_data$study_no)
meta_data$study_no

# assignment of article ids
meta_data <- transform(meta_data, id=match(authors_short, unique(authors_short)))
meta_data <- meta_data %>% 
        rename(article_id = id)

# creation of study identifier
meta_data$study_id <- paste(meta_data$article_id, meta_data$study_no, sep = "-")

# severity
meta_data$severity <- factor(meta_data$severity, levels = c("low", "medium", "high"))
 
# missing data
meta_data[meta_data == "not provided" ] <- NA
meta_data[meta_data == "not applicable" ] <- NA
 
# transformations
meta_data$pubyear <- as.numeric(as.character(meta_data$pubyear))
meta_data$m_age <- as.numeric(as.character(meta_data$m_age))
meta_data$percntg_females <- as.numeric(as.character(meta_data$percntg_females))

# compute Effect Size Variances
meta_data$var_d <- 1 / meta_data$n + (meta_data$cohens_d*meta_data$cohens_d)/(2*meta_data$n)
meta_data$var_d
```

# Density Plot
```{r, density, include = FALSE, fig.align="center"}

# Publication Year
# Barplot
avbyy_data <- meta_data %>%
  dplyr::group_by(aversion, pubyear) %>%
  dplyr::summarize(n = n()) %>% 
  dplyr::mutate(pct = n/sum(n),
                lbl = scales::percent(pct))

level_order <- c("1", "0")
avbyy_data$aversion <- factor(avbyy_data$aversion, levels=level_order)

avbyy_data$pubyear <- as.factor(avbyy_data$pubyear)
avbyy_data$aversion <- as.factor(avbyy_data$aversion)
aversion_by_year_plot <- ggplot(avbyy_data, aes(pubyear, y = n, fill = aversion))+
  geom_bar(stat = "identity", position = "dodge")+
  geom_text(aes(label = n, vjust = -0.5), position = position_dodge(width = 0.9))+
  labs(x = "Year of Publication", y = "Number of Studies")+ 
  theme_classic(base_size = 12) +
  theme(legend.position="top") + 
  scale_fill_grey(name = "Algorithm Aversion", labels = c("Observed", "Not Observed"))
aversion_by_year_plot

# Density Plot
# Create data
densitydata <- select(meta_data, pubyear, cohens_d, aversion)
densitydata$aversion <- as.factor(densitydata$aversion)

# Calculate means
library(plyr)
mu <- ddply(densitydata, "aversion", summarise, grp.mean=mean(pubyear))
head(mu)

densityplot <- ggplot(densitydata, aes(pubyear, fill = aversion))+
  geom_density() +
  geom_vline(data = mu, aes(xintercept=grp.mean, color = aversion), linetype="dashed", size=1)+
  labs(x = "Year of Publication", y = "Density")+ 
  theme_classic(base_size = 12)+ 
  scale_fill_grey(name = "Algorithm Aversion", labels = c("Observed", "Not Observed"))
densityplot

library(Cairo)
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
library(Cairo)
ggsave(filename = "aversion_by_year.png",
       plot = aversion_by_year_plot, dpi = 1000, width=6, height=5, type = "cairo")
```

# Cook's distance D, Forest, Caterpillar Plot
```{r, cooks_etal, include = FALSE, fig.align="center"}
## Multi-Level Random-Effects Meta-Regression Model
# Estimates Multi-level random-effects meta-regression model, without moderators
multilevel <- rma.mv(cohens_d, var_d, random = ~ 1 |
study_id/es_id, data = meta_data, method="ML")
multilevel

# Cook's distance D for each observed effect size (change in beta if one observation is dropped)
# Thresholds: D > 0.5 and > 1.0; D > 3*mean; D > 4/n; D > chisq(# regrcoeff, 0.50); any extreme D-value
cookdist1 <- cooks.distance(multilevel, progbar = TRUE, reestimate=FALSE)
plot(cookdist1, type="o", pch=19, xlab="Observed effect size", ylab="Cook's Distance")
```

# Forest Plot
```{r, forest, echo = TRUE, fig.align="center", fig.height=40, fig.width=10}
# Caterpillar Plot
forest(multilevel,
       addfit = TRUE,
       xlim=c(-3,2), # adjust horizontal plot region limits
       order="obs", # order by size of yi
       slab=NA, annotate=FALSE, # remove study labels and annotations
       efac=0, # remove vertical bars at end of CIs
       pch=19, # changing point symbol to filled circle
       col="gray40", # change color of points/CIs
       psize=2, # increase point size
       cex.lab=1, cex.axis=1, # increase size of x-axis title/labels
       xlab = "Effect Size (Cohen's d)",
       lty=c("solid","blank")) # remove horizontal line at top of plot

## Forest Plot ####
meta_data$cohens_d_plot <- format(round(meta_data$cohens_d, 2), nsmall = 2)
meta_data$cohens_d_plot <- as.numeric(meta_data$cohens_d_plot)

meta_data$pubyear <- as.numeric(as.character(meta_data$pubyear))
forest(multilevel,
       annotate = FALSE,
       addfit = TRUE,
       addpred = FALSE,
       showweights = FALSE,
       xlim=c(-10,1), # adjust horizontal plot region limits
       ilab=cbind(meta_data$pubyear, meta_data$study_no, meta_data$n, meta_data$cohens_d_plot),
       ilab.xpos=c(-5.40, -4.80, -4.30, -3.65),
       ilab.pos = 4,
       xlab = "Standardized Mean Difference",
       order="obs",
       header = TRUE, 
       slab = meta_data$authors_short)
op <- par(cex=1, font=2)
text(x = c(-5.40, -4.80, -4.30, -3.65), y = 213, label = c("Year","No.", "N", "d"), pos = 4)
par(op)

# Smaller Forest Plot 
newdata <- meta_data[order(meta_data$cohens_d_plot),]
newdata <- newdata[c(seq(1:20),seq(nrow(meta_data) - 20 + 1, nrow(meta_data))),]

multilevel <- rma.mv(cohens_d, var_d, random = ~ 1 |
study_id/es_id, data = newdata, method="ML")
multilevel

newdata$pubyear <- as.numeric(as.character(newdata$pubyear))
forest(multilevel,
       annotate = FALSE,
       addfit = FALSE,
       addpred = FALSE,
       showweights = FALSE,
       xlim=c(-10,1), # adjust horizontal plot region limits
       ilab=cbind(newdata$pubyear, newdata$study_no, newdata$n, newdata$cohens_d_plot),
       ilab.xpos=c(-5.40, -4.80, -4.30, -3.65),
       ilab.pos = 4,
       xlab = "Standardized Mean Difference",
       order="obs",
       header = TRUE, 
       slab = newdata$authors_short)
op <- par(cex=0.8, font=2)
text(x = c(-5.40, -4.80, -4.30, -3.65), y = 41.77, label = c("Year","No.", "N", "d"), pos = 4)
par(op)
```

# Box/ Bar Plots
```{r, boxbar, echo = TRUE, fig.align="center", fig.height=40, fig.width=10}
mods <- c("outlet", "discipline", "pubtype", "published", "within_subject", "field", "dv_cat", "subjective_perception", "dv_scaling", "dv_measurement_type", "compensation", "incentive_compatible", "preregistered", "online", "students", "location", "US", "sample_type", "domain", "management", "human_type", "expert", "algorithm_dummy", "ai_dummy", "textual", "severity", "subj_vs_obj")

# within_subject
within_subject_mod <- select(meta_data, cohens_d, within_subject, relevant_n)
within_subject_mod <- within_subject_mod[ which(within_subject_mod$within_subject=="yes" | within_subject_mod$within_subject == "no"), ]
within_subject_mod <- within_subject_mod[ which(within_subject_mod$relevant_n < 1501), ]

# box plot
within_subject_mod$within_subject <- as.factor(within_subject_mod$within_subject)
p1 <- ggplot(within_subject_mod, aes(x=within_subject, y=cohens_d, color = relevant_n)) + 
  geom_boxplot()+
  geom_boxplot(fill = "white")+
  geom_jitter(shape=16, position=position_jitter(0.2))+
  scale_color_gradient(low="darkgrey", high="red")+
  theme_classic(base_size = 15)+
  theme(legend.position="top")+
  scale_x_discrete(labels = c("Between\nSubjects","Within\nSubjects"))+
  labs(title="")+
  ylab("Effect Size (d)")+
  xlab("")+ 
  labs(color="N")
p1

# online
online_mod <- select(meta_data, cohens_d, online, relevant_n)
online_mod <- online_mod[ which(online_mod$online=="yes" | online_mod$online == "no"), ]
online_mod <- online_mod[ which(online_mod$relevant_n < 1501), ]

# box plot
online_mod$online <- as.factor(online_mod$online)
p2 <- ggplot(online_mod, aes(x=online, y=cohens_d, color = relevant_n)) + 
  geom_boxplot()+
  geom_boxplot(fill = "white")+
  geom_jitter(shape=16, position=position_jitter(0.2))+
  scale_color_gradient(low="darkgrey", high="red")+
  theme_classic(base_size = 15)+
  theme(legend.position="top")+
  scale_x_discrete(labels = c("Prolific/\nMturk\nSample","Non Prolific/\nMturk\nSample"))+
  labs(title="")+
  ylab("Effect Size (d)")+
  xlab("")+ 
  labs(color="N")
p2

# AI Dummy
ai_dummy_mod <- select(meta_data, cohens_d, ai_dummy, relevant_n)
ai_dummy_mod <- ai_dummy_mod[ which(ai_dummy_mod$ai_dummy=="yes" | ai_dummy_mod$ai_dummy == "no"), ]
ai_dummy_mod <- ai_dummy_mod[ which(ai_dummy_mod$relevant_n < 1501), ]

# box plot
ai_dummy_mod$ai_dummy <- as.factor(ai_dummy_mod$ai_dummy)
p3 <- ggplot(ai_dummy_mod, aes(x=ai_dummy, y=cohens_d, color = relevant_n)) + 
  geom_boxplot()+
  geom_boxplot(fill = "white")+
  geom_jitter(shape=16, position=position_jitter(0.2))+
  scale_color_gradient(low="darkgrey", high="red")+
  theme_classic(base_size = 15)+
  theme(legend.position="top")+
  scale_x_discrete(labels = c("AI Label\nAbsent","AI Label\nPresent"))+
  labs(title="")+
  ylab("Effect Size (d)")+
  xlab("")+ 
  labs(color="N")
p3

# DV Measurement Type
dv_measurement_type_mod <- select(meta_data, cohens_d, dv_measurement_type, relevant_n)
dv_measurement_type_mod <- dv_measurement_type_mod[ which(dv_measurement_type_mod$dv_measurement_type=="self-report" | dv_measurement_type_mod$dv_measurement_type == "behavioral"), ]
dv_measurement_type_mod <- dv_measurement_type_mod[ which(dv_measurement_type_mod$relevant_n < 1501), ]

# box plot
dv_measurement_type_mod$dv_measurement_type <- as.factor(dv_measurement_type_mod$dv_measurement_type)
p4 <- ggplot(dv_measurement_type_mod, aes(x=dv_measurement_type, y=cohens_d, color = relevant_n)) + 
  geom_boxplot()+
  geom_boxplot(fill = "white")+
  geom_jitter(shape=16, position=position_jitter(0.2))+
  scale_color_gradient(low="darkgrey", high="red")+
  theme_classic(base_size = 15)+
  theme(legend.position="top")+
  scale_x_discrete(labels = c("Behavioral","Self-Report"))+
  labs(title="")+
  ylab("Effect Size (d)")+
  xlab("")+ 
  labs(color="N")
p4

# Complexity
private_life_mod <- select(meta_data, cohens_d, private_life, relevant_n)
private_life_mod <- private_life_mod[ which(private_life_mod$private_life=="no" | private_life_mod$private_life == "yes"), ]
private_life_mod <- private_life_mod[ which(private_life_mod$relevant_n < 1501), ]

# box plot
private_life_mod$private_life <- as.factor(private_life_mod$private_life)
p5 <- ggplot(private_life_mod, aes(x=private_life, y=cohens_d, color = relevant_n)) + 
  geom_boxplot()+
  geom_boxplot(fill = "white")+
  geom_jitter(shape=16, position=position_jitter(0.2))+
  scale_color_gradient(low="darkgrey", high="red")+
  theme_classic(base_size = 15)+
  theme(legend.position="top")+
  scale_x_discrete(labels = c("Low\nComplexity\nSetting","High\nComplexity\nSetting"))+
  labs(title="")+
  ylab("Effect Size (d)")+
  xlab("")+ 
  labs(color="N")
p5

# US
US_mod <- select(meta_data, cohens_d, US, relevant_n)
US_mod <- US_mod[ which(US_mod$US=="yes" | US_mod$US == "no"), ]
US_mod <- US_mod[ which(US_mod$relevant_n < 1501), ]

# box plot
US_mod$US <- as.factor(US_mod$US)
p6 <- ggplot(US_mod, aes(x=US, y=cohens_d, color = relevant_n)) + 
  geom_boxplot()+
  geom_boxplot(fill = "white")+
  geom_jitter(shape=16, position=position_jitter(0.2))+
  scale_color_gradient(low="darkgrey", high="red")+
  theme_classic(base_size = 15)+
  theme(legend.position="top")+
  scale_x_discrete(labels = c("Non-US\nSample","US\nSample"))+
  labs(title="")+
  ylab("Effect Size (d)")+
  xlab("")+ 
  labs(color="N")
p6

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
library(Cairo)
ggsave(filename = "p1.png",
       plot = p1, dpi = 1000, width=3, height=5, type = "cairo")
ggsave(filename = "p2.png",
       plot = p2, dpi = 1000, width=3, height=5, type = "cairo")
ggsave(filename = "p3.png",
       plot = p3, dpi = 1000, width=3, height=5, type = "cairo")
ggsave(filename = "p4.png",
       plot = p4, dpi = 1000, width=3, height=5, type = "cairo")
ggsave(filename = "p5.png",
       plot = p5, dpi = 1000, width=3, height=5, type = "cairo")
ggsave(filename = "p6.png",
       plot = p6, dpi = 1000, width=3, height=5, type = "cairo")
```
