title: AI Resistance Meta-Analysis
description: This is an overview 
theme: just-the-docs

url: https://childebrand.github.io/metaAI

aux_links: # remove if you don't want this link to appear on your pages
  GitHub Repository: https://github.com/childebrand/metaAI


